### ISSUE TITLE
Issues with genetic distance.

### ISSUE THREAD

**Issue by grabear** [gusevlab/germline#5]
I'm working with some non-human primate data that I would like to run through the PADRE.  In order to get it there I'm using plink/primus, and then beagle/germline/ersa.  

After running beagle and breaking up the VCF output by chromosome, I generated .match files using germline.  I would like to continue the pipeline with ersa, but I need the genetic distance in cM instead of MB.  How can I convert the MB column to cM?

Here is the germline command that I use..

```shell
germline -input $PLINK_PREFIX.ped $PLINK_PREFIX.map -output $OUTFILE -err_hom 2 -err_het 1 -min_m 2.5cM
```

**Comment by grabear** [comment]
@sdhutchins

**Comment by sashagusev** [comment]
Hi Rob, you should add a `-map` flag to the run and point it to a plink format map file that has centimorgans in the third column (it can be exactly the same map file as used for input). Then the output will be in cM and you won't have issues with MB -> cM conversion (which I wouldn't recommend).

BTW, I would also change the flag to `-min_m 2.5` because characters in the parameter can mess up the run.

**Comment by grabear** [comment]
Ok thank you @sashagusev!  I will try that out.  I will say that I have looked at my plink .map file, and the 3rd column is actually just a bunch of 0's.  Could this be an issue as well?

**Comment by grabear** [comment]
I'm running with `-map` on our cluster right now, so I will let you guys know the results.

**Comment by sashagusev** [comment]
Great, the way germline works is it looks in the `-map` file for the third column cM position, if it's not there it then looks in the provided *.map file for the third column, and if it's not there it just uses the megabase positions. So 0's in the column won't strictly mess things up but we strongly recommend providing the cM information if it's available as that substantially increases accuracy.

**Comment by grabear** [comment]
Ok, I see  I was worried about this before starting the analysis, but I wasn't sure how it was going to resurface.

We still aren't getting cM information from germline (it continues to output in MB).  So, how do we generate the genetic distance info in cM?  What software do we use?

**Comment by sashagusev** [comment]
I haven't had a lot of experience with non-human data but this information should be contained in a public recombination/genetic map. For example, Auton et al. mapped recombination in chimps and that data is available here:
http://panmap.uchicago.edu/data.html

You would then need to create a plink format map file that contains the cM distance from start of chromosome for each marker (or you can interpolate the distance across markers if your data doesn't perfectly match the markers in the map).

**Comment by grabear** [comment]
Thanks for the push in the right direction, @sashagusev!  🙌  Our PI is actually authored on a paper that utilizes a Rhesus macaque genetic map, which is what we need.

**Comment by sashagusev** [comment]
Perfect! Let me know if you still run into any issues.

**Comment by grabear** [comment]
Hey @sashagusev I thought I would get in touch with you here again.

As stated before we ran beagle, and then broke up the large VCF file by chromosome.  After generating plink files, we then ran germline.  However, my output may be wrong.  The first 4 columns of my .match file seem incorrect to me.

- Family ID 1
- Individual ID 1
- Family ID 2
- Individual ID 2

As seen below the first 50 to 100 rows use the Individual ID 1, but eventually, they become sequences instead of the animal name.  Additionally, the Family ID 1 is the same as the Individual ID 1, and each '_chromosome_.match' file uses only 1 Individual ID (**m02195**).  There's also the issue with Family ID 2 and Individual ID 2 being a sequence throughout the entire file.

![image](https://user-images.githubusercontent.com/20953530/71631415-30310e00-2bce-11ea-9bff-53a129742eb8.png)

Here are my questions:

- Does this have something to do with my use of plink, germline, or bcftools?
- Our files are technically BCF files, is this an issue?
- ~I don't think we have Family IDs associated with our data.  Is that an issue?~

**Comment by grabear** [comment]
I took a look at your test data [here](https://github.com/gusevlab/germline/blob/master/test/expected.match), and I can see that you don't have any associated family IDs.  So I'll cross that question out.

**Comment by sashagusev** [comment]
Hey, sorry for the delay, this looks like the input files are being garbled, there should be no sequence showing up in the output at all. How are you converting VCF->plink format? Can you double check that only bi-allelic, single nucleotide variants are going into the output and that the resulting ped and map files have the expected number of rows and columns? It is common for VCFs to contain other variants that will break the output.

**Comment by grabear** [comment]
Hi @sashagusev.  I wouldn't have expected you to answer right away with the holidays.  Thanks for coming back to this issue, and continuing to help with our analysis.

We are attempting the PADRE pipeline:

![image](https://user-images.githubusercontent.com/20953530/72370983-faf5e700-36c8-11ea-9616-88e35e066e6d.png)

So we have data that has been filtered by GATK.  We manually do some preprocessing with bcftools before this pipeline as well.  Our VCF data is huge, so part of our strategy is to remove unnecessary data in order to reduce the size of the file.  (See below)

```shell
...
VCF=${MY_DIR}/all_data.vcf.gz
IDS=INFO/ANN,INFO/CADD_PH,INFO/CADD_RS,INFO/CCDS,INFO/ENC,INFO/ENCDNA_CT,INFO/ENCDNA_SC,INFO/ENCSEG_CT,INFO/ENCSEG_NM,INFO/ENCTFBS_CL,INFO/ENCTFBS_SC,INFO/ENCTFBS_TF,INFO/ENN,INFO/ERBCTA_CT,INFO/ERBCTA_NM,INFO/ERBCTA_SC,INFO/ERBSEG_CT,INFO/ERBSEG_NM,INFO/ERBSEG_SC,INFO/ERBSUM_NM,INFO/ERBSUM_SC,INFO/ERBTFBS_PB,INFO/ERBTFBS_TF,INFO/FC,INFO/FE,INFO/FS_EN,INFO/FS_NS,INFO/FS_SC,INFO/FS_SN,INFO/FS_TG,INFO/FS_US,INFO/FS_WS,INFO/GRASP_AN,INFO/GRASP_P,INFO/GRASP_PH,INFO/GRASP_PL,INFO/GRASP_PMID,INFO/GRASP_RS,INFO/LF,INFO/LOF,INFO/NC,INFO/NE,INFO/NF,INFO/NG,INFO/NH,INFO/NJ,INFO/NK,INFO/NL,INFO/NM,INFO/NMD,INFO/OMIMC,INFO/OMIMD,INFO/OMIMM,INFO/OMIMMUS,INFO/OMIMN,INFO/OMIMS,INFO/OMIMT,INFO/OREGANNO_PMID,INFO/OREGANNO_TYPE,INFO/PC_PL,INFO/PC_PR,INFO/PC_VB,INFO/PP_PL,INFO/PP_PR,INFO/PP_VB,INFO/RDB_MF,INFO/RDB_WS,INFO/RFG,INFO/RSID,INFO/SCSNV_ADA,INFO/SCSNV_RS,INFO/SD,INFO/SF,INFO/SM,INFO/SP_SC,INFO/SX,INFO/TMAF,INFO/CLN_ALLELE,INFO/CLN_ALLELEID,INFO/CLN_DBVARID,INFO/CLN_DISDB,INFO/CLN_DISDBINCL,INFO/CLN_DN,INFO/CLN_DNINCL,INFO/CLN_GENEINFO,INFO/CLN_HGVS,INFO/CLN_MC,INFO/CLN_ORIGIN,INFO/CLN_REVSTAT,INFO/CLN_RS,INFO/CLN_SIG,INFO/CLN_SIGINCL,INFO/CLN_SSR,INFO/CLN_VC,INFO/CLN_VCSO,INFO/CLN_VI
OUTFILE1=${MY_DIR}/all_data_rminfo.vcf.gz
INFILE=${MY_DIR}/all_data_rminfo.vcf.gz
OUTFILE2=${MY_DIR}/all_data_rminfo_norm.vcf.gz
FASTA=${MY_DIR}/ref_genome/1_Mmul_8.0.1.fasta

# Remove IDs
bcftools annotate $VCF -x $IDS -O z -o $OUTFILE1 --threads 40
bcftools index $OUTFILE1 --threads 40

# Normalize the file by removing duplicates
bcftools norm $INFILE-d both -f $FASTA-O z -o $OUTFILE2--threads 85
bcftools index $OUTFILE2--threads 85

```

After beagle finishes running, we split the corresponding output up into VCF files by chromosome, and convert the files to PLINK format.

```shell
# First index the beagle vcf file for bcftools
bcftools index TNPRC-beagle.vcf.gz

# Next split the vcf files by chromosome and then put them in plink format
chromosomes="chr01 chr02 chr03 chr04 chr05 chr06 chr07 chr08 chr09 chr10 chr11 chr12 chr13 chr14 chr15 chr16 chr17 chr18 chr19 chr20 chrUn chrX chrY MT"
for chromo in $chromosomes
do
  echo $chromo
  eval "bcftools view -r $chromo -o TNPRC-phased-$chromo.vcf.gz TNPRC-phased.vcf.gz -Oz"
  eval "plink --vcf TNPRC-phased-$chromo.vcf.gz --recode --out TNPRC-phased-$chromo --allow-extra-chr"
done
```

@sdhutchins is running a script that will make all of our data bi-allelic.  Once it finishes, I will run beagle and then germline to see if that helps.  Meanwhile, do you have any other suggestions based on the way we've filtered our data?

**Comment by sashagusev** [comment]
Gotcha, this all looks good and I strongly suspect that either non bi-allelic sites or indel sites (with alleles that are more than just A/C/G/T) is the culprit. If you want a quick check you can remove these sites from the final plink vcf -> ped conversion (I don't think removing them *after* phasing is a problem) and see if GERMLINE works better.
