### ISSUE TITLE
germline command not found

### ISSUE THREAD

**Issue by sagitaninta** [gusevlab/germline#6]
I keep failing in calling the `germline` command in my local machine. I have followed all instructions in http://gusevlab.org/projects/germline/usage.html (download, extract, make all inside the extracted directory and make test) and the `make all` and `make test` command works just fine, but everytime I called `germline`, the prompt always give me this error message.
```
-bash: germline: command not found
```

I also added the path to the whole directory of germline-1-5-3 but still cannot execute any `germline` command. Please let me know if I missed something in the installation.

**Comment by sashagusev** [comment]
Hello, does the germline binary file exist? Can you try calling the full path to the germline binary?
________________________________

**Comment by sagitaninta** [comment]
After I call the full path to germline binary in my local machine, it said
```
-bash: ./germline: cannot execute binary file
```

But then even if I can execute this, it means that I cannot call it just by typing `germline` in the command line. I have to specify the path (which I can do by modifying my profile) which may be a bit inconvenient if I want to automate my pipeline.

Interestingly, I can install and call germline in my university's HPC with the following warning
```
./germline: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./germline)
./germline: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./germline)
./germline: /lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ./germline)
```

I was advised to load `gcc` in the cluster before running germline and it worked, but the IT said that it may conflict when I submit a job when there is different version.

Coming back to my local machine, I think the issue is with MacOS handle `gcc` differently than Linux so that I cannot execute the germline binary file. I am not quite sure what to do about this. I have even tried to create tap of germline in my Homebrew library, MacOS package manager, containing the whole germline directory in the GitHub, but it keeps giving me various error and warning messages.

**Comment by sashagusev** [comment]
I’m surprised that `make` and `make test` were able to run successfully, are you sure you didn’t get any errors?

Can you try running `chmod u+x germline` to make sure that it is executable? If you are able to get germline running with the full path then it’s just a matter of making sure the path is added correctly to your PATHS variable to get it running without the full path.

**Comment by sashagusev** [comment]
I just tried the following on my mac:

```
tar xzvf germline-1-5-3.tar.gz
cd germline-1-5-3
make
./germline 
```

and it works. Can you try these commands and make sure you are calling the right germline binary.

**Comment by sagitaninta** [comment]
I have tried that and it worked, thanks!

`make all` ran with several warnings but `make test` works just fine. I do not know if opening the tar.gz file through Finder was doing something because that and `make all` were the only steps that are different.

**Comment by sashagusev** [comment]
Great!  Sounds like it was just some mac wonkiness.
